apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-monitoring

resources:
  - namespace.yaml
  - rbac.yaml
  - configmaps.yaml
  - app-deployment.yaml
  - app-service.yaml
  - ml-deployment.yaml
  - ml-service.yaml

commonLabels:
  app.kubernetes.io/part-of: ai-monitoring-system
