apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: ai-monitoring
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: ml-anomaly-detector
  namespace: ai-monitoring
spec:
  type: NodePort
  ports:
    - port: 8001
      targetPort: 8001
      nodePort: 30081
      name: http
